/* Gabriel Nowak, 19.01.2018
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
import static java.lang.System.out;
public class euler2 {
    static int findFibEvenSum(int max)
    {
        int a=1;
        int b=1;
        int c,sum;
        sum=0;
        while(a<max)
        {
            if(a%2==0)sum+=a;
            c=a+b;
            a=b;
            b=c;
        }
        return sum;
    }
    public static void main(String args[])
    {
        int score=findFibEvenSum(4000000);
        out.print(score);

    }
}
